SELECT *
FROM EMPLOYEES;

/*
    1. COLUMN ALIASES --> IT IS TEMPRORARY NAME TO SHOW IN DISPLAY
    2. TABLE ALIASES -->
 */
--DISPLAY DEPARTMENTS WHERE THEIR AVG SALARY MORE THAN 6K
-- THE QUERY BELOW SECOND COLUMN IS ROUND(AVG(SALARY), 2)
SELECT JOB_ID, ROUND(AVG(SALARY), 2) AS "AVEREGE SALARY"
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL -- TO REMOVE NULL DEPARTMENT ID FROM TABLE
GROUP BY JOB_ID
HAVING AVG(SALARY) > 6000
ORDER BY 2 DESC;

SELECT JOB_ID, ROUND(AVG(SALARY), 2) AS AVEREGE_SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL -- TO REMOVE NULL DEPARTMENT ID FROM TABLE
GROUP BY JOB_ID
HAVING AVG(SALARY) > 6000
ORDER BY 2 DESC;

--MANAGER IS ASKING DISPLAY ANNUAL SALARY FOR ALL EMPLOYEES AS ANNUAL_SALARY
SELECT FIRST_NAME, (SALARY * 12) AS ANNUAL_SALARY
FROM EMPLOYEES;

--NOTE WE ARE JUST DISPLAYING AND NOTHING WILL CHANGE IT DB

---------------STRING MANIPULATION---------------------
-- I WANT TO GET FULL NAME COLUMN WHERE WE HAVE FIRST NAME +' '+LAST NAME
/*
    CONCAT
    --JAVA --> FIRST_NAME+" "+LAST_NAME
    --SQL--> || FIRST_NAME ||' '||LAST_NAME
 */
SELECT FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME
FROM EMPLOYEES;

--ADD @CYDEO.COMTO ALL THE EMAILS IN THE EMPLOYEE TABLE
SELECT EMAIL || '@CYDEO.COM' AS EMAIL
FROM EMPLOYEES;

SELECT CONCAT(EMAIL, '@CYDEO.COM')
FROM EMPLOYEES;

SELECT LOWER(EMAIL || '@CYDEO.COM') AS EMAIL
FROM EMPLOYEES;
SELECT UPPER(EMAIL || '@CYDEO.COM') AS EMAIL
FROM EMPLOYEES;
SELECT INITCAP(EMAIL || '@CYDEO.COM') AS EMAIL
FROM EMPLOYEES;-->IT MAKE FIRST LETTER UPPER CASE

SELECT EMAIL, LENGTH(EMAIL) AS EMAIL_LENGTH
FROM EMPLOYEES;

--DISPLAY ALL EMPLOYEES WHERE FIRSTNAME LENGTH EQUALST TO 6
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) = 6;

--ANOTHER SOLUTION
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '______';

--HOW MANY QUESTION
SELECT COUNT(*)
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '______';

--DISPLAY INITIALS FROM FIRST NAME AND LAST NAME -->S.K,-----N.K
--SUBSTR(COLUMN NAME ,BEGINING INDEX,NUMBER OF CHAR)
SELECT *
FROM EMPLOYEES;
SELECT SUBSTR(FIRST_NAME, 0, 1) || '.' || SUBSTR(LAST_NAME, 0, 1) || '.' AS INITIALS
FROM EMPLOYEES;

SELECT FIRST_NAME, SUBSTR(FIRST_NAME, -2, 2)
FROM EMPLOYEES;
--MINUS STARTS FROM END

/*
    -IF BEGGINING INDEX IS 0, IT IS TREATED AS 1
    -IF THE BEGGINING INDEX NEGATIVE, IT WILL START FROM BACKWARDS
    -IF WE DONT SPECIFY NUMBER OF CHAR IT WILL WORK TILL THE END
 */