SELECT *
FROM EMPLOYEES;

--YOUR MANAGER IS ASKING ALL JOBS AND THEIR AVERAGE SALARY
SELECT DISTINCT JOB_ID
FROM EMPLOYEES;

--DISPLAY AVERAGE SALARY FOR IT PROGRAMMER
SELECT AVG(SALARY)
FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';

SELECT JOB_ID, AVG(SALARY), COUNT(*), SUM(SALARY), MIN(SALARY), MAX(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY SUM(SALARY) DESC;

--DISPLAY HOW MANY DEPARTMENTS WE HAVE IN EACH LOCATIONS?
SELECT LOCATION_ID, COUNT(*)
FROM DEPARTMENTS
GROUP BY LOCATION_ID;

--ORDER RESULT BASED ON NUMBER OF DEPARTMENTS DESC
SELECT LOCATION_ID, COUNT(*)
FROM DEPARTMENTS
GROUP BY LOCATION_ID
ORDER BY COUNT(*) DESC;

SELECT LOCATION_ID, COUNT(*) C
FROM DEPARTMENTS
GROUP BY LOCATION_ID
ORDER BY C DESC;

SELECT LOCATION_ID, COUNT(*)
FROM DEPARTMENTS
GROUP BY LOCATION_ID
ORDER BY 2 DESC;

--DISPLAY HOW MANY COUNTRIES WE HAVE IN EACH REGIONS
SELECT REGION_ID, COUNT(*)
FROM COUNTRIES
GROUP BY REGION_ID;

--ORDER THEM BASED ON NUMBER OF COUNTRIES IN DESC
SELECT REGION_ID, COUNT(*)
FROM COUNTRIES
GROUP BY REGION_ID
ORDER BY 2 DESC;

--GET ME TOTAL SALARY FROM EACH DEPARTMENTS FROM EMPLOYEES TABLE.
SELECT DEPARTMENT_ID, SUM(SALARY), COUNT(*)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL --TO REMOVE NULL DEPARTMENT ID FROM THE RESULT
GROUP BY DEPARTMENT_ID;

--DISPLAY JOB ID WHERE THEIR AVG SALARY MORE THAN 5K
SELECT JOB_ID, AVG(SALARY)
FROM EMPLOYEES
HAVING AVG(SALARY) > 5000
GROUP BY JOB_ID;

--DISPLAY DEPARTMENTS WHERE THEIR AVG SALARY MORE THAN 6K
SELECT JOB_ID, ROUND(AVG(SALARY), 2)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL -- TO REMOVE NULL DEPARTMENT ID FROM TABLE
GROUP BY JOB_ID
HAVING AVG(SALARY) > 6000
ORDER BY 2 DESC;

--INTERVIEW QUESTION--DISPLAY DUPLICATE (MORE THAN ONE) FIRSTNAME FROM EMPLOYEES TABLE
SELECT FIRST_NAME, COUNT(*)
FROM EMPLOYEES
HAVING COUNT(*) > 1
GROUP BY FIRST_NAME;

--DISPLAY DEPARTMENT ID WHERE EMPLOYEES COUNT IS BIGGER THAN 5
SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 5
ORDER BY 2 DESC ;