SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MANAGER_ID FROM EMPLOYEES;

--WHO IS THE NEENA MANAGER IN THIS TABLE, W --> WORKERS , M --> MANAGER
SELECT W.EMPLOYEE_ID,W.FIRST_NAME,W.LAST_NAME,
MANAGERS.MANAGER_ID,MANAGERS.FIRST_NAME,MANAGERS.LAST_NAME FROM EMPLOYEES W
JOIN EMPLOYEES MANAGERS ON W.MANAGER_ID=MANAGERS.EMPLOYEE_ID;

--HOW CAN I SEE ALL EMPLOYEES EVEN IF THEY DONT HAVE ANY MANAGER
SELECT W.EMPLOYEE_ID,W.FIRST_NAME,W.LAST_NAME,
M.MANAGER_ID,M.FIRST_NAME,M.LAST_NAME FROM EMPLOYEES W
LEFT JOIN EMPLOYEES M ON W.MANAGER_ID=M.EMPLOYEE_ID
ORDER BY 1 ASC ;