-- SELECT * FROM EMPLOYEES;
/*
 IT SHOWS DIFFERENT VALUES FROM QUERY RESULT BASED PROVIDED COLUMN
 */
--IT RETURNS 107 RESULT
SELECT FIRST_NAME FROM EMPLOYEES;

--IT REMOVED DUPLICATES AND RETURNS 91 RESULT
SELECT DISTINCT FIRST_NAME FROM EMPLOYEES;

SELECT * FROM JOBS;

SELECT JOB_ID FROM JOBS;

--SINCE PRIMARY KEY CAN NOT BE DUPLICATE IT GIVES THE SAME RESULT WITH DISTINCT
SELECT DISTINCT JOB_ID FROM JOBS;