SELECT *
FROM EMPLOYEES;

CREATE TABLE scrumteam
(
    emp_id     INTEGER PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name  VARCHAR(20) NOT NULL,
    job_title  VARCHAR(20),
    salary     INTEGER
);
INSERT INTO SCRUMTEAM(EMP_ID, FIRST_NAME, LAST_NAME, JOB_TITLE, SALARY)
VALUES (1, 'MAHIR', 'SARAC', 'SDET', 130000);

INSERT INTO SCRUMTEAM(EMP_ID, FIRST_NAME, LAST_NAME, JOB_TITLE, SALARY)
VALUES (2, 'MIKE', 'SMITH', 'BACK END DEVELOPER', 140000);
INSERT INTO SCRUMTEAM(EMP_ID, FIRST_NAME, LAST_NAME, JOB_TITLE, SALARY)
VALUES (3, 'JOE', 'BARRACK', 'PO', 180000);
commit;
-- save changes so that other peopke connections can get the updates

UPDATE SCRUMTEAM
SET SALARY=SALARY + 5000;

UPDATE SCRUMTEAM
SET SALARY=150000
WHERE EMP_ID = 1;

DELETE SCRUMTEAM
WHERE EMP_ID = 3;
SELECT *
FROM SCRUMTEAM;
--CRUD
--CREATE(INSERT)
--READ(SELECT)
--UPDATE(UPDATE)
--DELETE(DELETE)

--ALTER
--ADD NEW COLUMN
ALTER TABLE SCRUMTEAM
ADD GENDER VARCHAR(10);

UPDATE SCRUMTEAM
SET GENDER='MALE'
WHERE EMP_ID = 1;

SELECT *
FROM SCRUMTEAM;
--RENAME THE COLUMN
ALTER TABLE SCRUMTEAM RENAME
    COLUMN SALARY TO ANNUAL_SALARY;

--DROP COLUMN
ALTER TABLE SCRUMTEAM
    DROP COLUMN GENDER;

--RENAME TABLE
ALTER TABLE SCRUMTEAM RENAME TO AGILE_TEAM;

--TRUNCATE
TRUNCATE TABLE AGILE_TEAM;

--DROP TABLE
DROP TABLE AGILE_TEAM;

/*
 WHAT IS THE DIFFERENCE BETWEEN TRUNCATE AND DROP
 TRUNCATE--> IT WILL DELETE TABLE CONTENT BUT KEEP THE TABLE
 DROP--> IT WILL DELETE ALL CONTENT AND TABLE ITSELF
 */