SELECT *
FROM EMPLOYEES;

--TASK: HOW MANY LOCATIONS WE HAVE FOR EACH COUNTRY

SELECT COUNTRY_ID, COUNT(*)
FROM LOCATIONS
GROUP BY COUNTRY_ID;

--ORDER THEM BASE ON COUNTRY ID
SELECT COUNTRY_ID, COUNT(*)
FROM LOCATIONS
GROUP BY COUNTRY_ID ORDER BY COUNTRY_ID;

--WHAT IF I WANT TO SEE US,UK,CA
SELECT COUNTRY_ID, COUNT(*)
FROM LOCATIONS
WHERE COUNTRY_ID IN ('US','UK','CA')
GROUP BY COUNTRY_ID;

--DISPLAY WHERE LOCATION COUNT IS BIGGER THAN 2
SELECT COUNTRY_ID, COUNT(*)
FROM LOCATIONS
GROUP BY COUNTRY_ID
HAVING COUNT(*)>2;

--TASK2 DISPLAY ALL EMPLOYEES ALL SALARY IN FOLLOWING FORMAT AS COLUMN NAME  EMPLOYEES SALARY
    --EXAMPLE STEVEN MAKES 24000K

SELECT FIRST_NAME||' MAKES '||SALARY AS EMPLOYEE_SALARY FROM EMPLOYEES;