SELECT *
FROM EMPLOYEES;

--DISPLAY ALL INFORMATION WHO IS MAKING MAXIMUM SALARY
SELECT *
FROM EMPLOYEES
WHERE SALARY = 24000;

--IF STEVEN KING SALARY CHANGES WE CAN FIND AGAIN MAXIMUM SALARY WITH DYNAMIC WAY
--DYNAMIC RESULT
SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);
--GIVE ME ALL INFORMATION WHO IS GETTING MINIMUM SALARY
SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);

--DISPLAY ALL THE INFORMATION WHO IS GETTING SECOND HIGHEST SALARY
SELECT *
FROM EMPLOYEES
WHERE SALARY =
      (SELECT MAX(SALARY)
       FROM EMPLOYEES
       WHERE SALARY <
             (SELECT MAX(SALARY) FROM EMPLOYEES));
SELECT *
FROM EMPLOYEES
WHERE SALARY <
      (SELECT MAX(SALARY)
       FROM EMPLOYEES) AND ROWNUM<=2; --IT GIVES ONLY TWO PEOPLE WHO IS MAKING SECOND HIGHEST SALARY

--TASK DISPLAY ALL INFORMATION WHO IS GETTING MORE THEN AVERAGE
SELECT * FROM EMPLOYEES WHERE SALARY>(SELECT AVG(SALARY) FROM EMPLOYEES);