SELECT *
FROM CUSTOMER;

SELECT FIRST_NAME, LAST_NAME, ADDRESS, PHONE
FROM CUSTOMER
JOIN ADDRESS A
ON A.ADDRESS_ID = CUSTOMER.ADDRESS_ID;

--Q WHAT IF I WANT TO SEE CUSTOMER TABLE INFORMATION TOO.

SELECT FIRST_NAME, LAST_NAME, C.ADDRESS_ID, A.ADDRESS_ID, ADDRESS, PHONE
FROM CUSTOMER C
JOIN ADDRESS A
ON C.ADDRESS_ID = A.ADDRESS_ID;

--TABLE ALIASES
--CUSTOMER-> C EMPLOYEES-> E  ADDRESS-> A

--INNER JOIN AND JOIN IS SAME AND RESULT RETURNS ONLY INTERSECTION
SELECT FIRST_NAME, LAST_NAME, C.ADDRESS_ID, A.ADDRESS_ID, ADDRESS, PHONE
FROM CUSTOMER C
JOIN ADDRESS A
ON C.ADDRESS_ID = A.ADDRESS_ID;

/*
 LEFT OUTER JOIN / LEFT JOIN
 --IT WILL GIVE MATCHING PART BETWEEN TWO TABLES + UNIQUE FOR LEFT TABLE
 --THE ORDER OF THE TABLE IS IMPORTANT
 */
SELECT FIRST_NAME, LAST_NAME, C.ADDRESS_ID, A.ADDRESS_ID, ADDRESS, PHONE
FROM CUSTOMER C
LEFT OUTER JOIN ADDRESS A
ON C.ADDRESS_ID = A.ADDRESS_ID;

/*
 RIGHT OUTER JOIN / RIGHT JOIN
 --IT WILL GIVE MATCHING PART BETWEEN TWO TABLES + UNIQUE FOR RIGHT TABLE
 --THE ORDER OF THE TABLE IS IMPORTANT
 */
SELECT FIRST_NAME, LAST_NAME, C.ADDRESS_ID, A.ADDRESS_ID, ADDRESS, PHONE
FROM CUSTOMER C
RIGHT OUTER JOIN ADDRESS A
ON C.ADDRESS_ID = A.ADDRESS_ID;

/*
 FULL OUTER JOIN / FULL JOIN
 --IT WILL GIVE MATCHING PART BETWEEN TWO TABLES + UNIQUE FOR ALL TABLE
 --THE ORDER OF THE TABLE IS NOT IMPORTANT
 */
SELECT FIRST_NAME, LAST_NAME, C.ADDRESS_ID, A.ADDRESS_ID, ADDRESS, PHONE
FROM CUSTOMER C
FULL OUTER JOIN ADDRESS A
ON C.ADDRESS_ID = A.ADDRESS_ID;