SELECT  * FROM EMPLOYEES;

-- DISPLAY ALL FIRST_NAME AND RELATED DEPARTMENTS NAME

SELECT FIRST_NAME,DEPARTMENT_NAME FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

--ORDER THE LIST BASED ON FIRSTNAME ASC
SELECT FIRST_NAME,DEPARTMENT_NAME FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
ORDER BY FIRST_NAME;

--display all first_name and department name including the employee without department

SELECT FIRST_NAME,DEPARTMENT_NAME FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
ORDER BY FIRST_NAME;

--3DISPLAY ALL FIRST_NAME AND DEPARTMENT_NAME INCLUDING THE DEPARTMENT WITHOUT EMPLOYEE
SELECT FIRST_NAME,DEPARTMENT_NAME FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

--HOW MANY EMPLOYEE WE HAVE FOR EACH DEPARTMENT NAME
SELECT DEPARTMENT_NAME,COUNT(*) FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;

--DISPLAY ALL FIRST NAME AND DEPARTMENT NAME INCLUDING THE DEPARTMENT WITHOUT
-- EMPLOYEES AND ALSO EMPLOYEES WITHOUT DEPARTMENT
SELECT FIRST_NAME,DEPARTMENT_NAME FROM EMPLOYEES E
FULL JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

--DISPLAY ALL CITIES AND ALL RELATED COUNTRY NAMES
SELECT CITY,COUNTRY_NAME FROM LOCATIONS L
JOIN COUNTRIES C ON L.COUNTRY_ID=C.COUNTRY_ID;

--DISPLAY ALL CITIES AND ALL RELATED COUNTRY NAMES INCLUDING WITH COUNTRIES WITHOUT CITIES
SELECT CITY,COUNTRY_NAME FROM LOCATIONS L
RIGHT JOIN COUNTRIES C ON L.COUNTRY_ID=C.COUNTRY_ID;

--DISPLAY ALL DEPARTMENT NAME AND RELATED STREET ADDRESS
SELECT DEPARTMENT_NAME,L.LOCATION_ID, STREET_ADDRESS FROM DEPARTMENTS D
JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID;

--DISPLAY FIRST NAME AND LASTNAME AND DEPARTMENT NAME CITY FOR ALL EMPLOYEES
SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_NAME,CITY FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID JOIN LOCATIONS L
ON D.LOCATION_ID=L.LOCATION_ID;

--DISPLAY FIRST NAME AND LASTNAME AND DEPARTMENT NAME CITY AND COUNTRY_NAME FOR ALL EMPLOYEES
SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_NAME,CITY,COUNTRY_NAME,REGION_NAME FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID
JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
JOIN REGIONS R ON R.REGION_ID=C.REGION_ID;

--HOW MANY EMPLOYEES WORKING FOR EACH COUNTRY_NAME
SELECT COUNTRY_NAME,COUNT(*) FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID
JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
GROUP BY COUNTRY_NAME
HAVING COUNT(*)>10;

--LEFT JOIN WITH WHERE
SELECT * FROM CUSTOMER C FULL JOIN ADDRESS A
ON A.ADDRESS_ID=C.ADDRESS_ID
WHERE C.ADDRESS_ID IS NULL OR C.ADDRESS_ID IS NULL;